<a href="https://colab.research.google.com/github/AnkitaSahu1312/AnkitaSahu1312/blob/main/Exp2_DL_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



**Write a program to implement different activation function used in deep learning**




In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

def relu(x):
    return np.maximum(0, x)

def leaky_relu(x, alpha=0.01):
    return np.maximum(alpha * x, x)

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)


In [ ]:
x = np.array([-1, 0, 1])

# Sigmoid
print(sigmoid(x))

[0.26894142 0.5        0.73105858]


In [ ]:
# Tanh
print(tanh(x))

[-0.76159416  0.          0.76159416]


In [ ]:
# ReLU
print(relu(x))

[0 0 1]


In [ ]:
# Leaky ReLU
print(leaky_relu(x))

[-0.01  0.    1.  ]


In [ ]:
# Softmax
print(softmax(x))

[0.09003057 0.24472847 0.66524096]
